//
//  Constants.swift
//  Fintoo
//
//  Created by iosdevelopermme on 24/02/18.
//  Copyright © 2018 iosdevelopermme. All rights reserved.
//

import Foundation
struct Constants {
   static let BASE_URL =  "https://www.financialhospital.in/adminpanel/"
    //static let BASE_URL =  "http://www.erokda.in/adminpanel/"
    static let BASE_URL1 = "https://www.financialhospital.in/adminpanel/"
    static let OTP_LIMIT = 6
    static let ERROR_CODE_1001 = "1001"
    static let ERROR_CODE_1002 = "1002"
    static let ERROR_CODE_1003 = "1003"//Email Id Already Exists
    static let ERROR_CODE_1004 = "1004"//Mobile No Already Exists
    static let ERROR_CODE_1005 = "1005" //Email and Mobile Already Exists
    static let ERROR_CODE_1701 = "1701"
    static let ERROR_CODE_1006 = "1006" // register Failed
    static let ERROR_CODE_1007 = "1007" //OTP Failed To Sent on Mail




    struct ViewControllers {
        static let MOBILE_NUMBER_VIEW_CONTROLLER = "MobileNumberViewController"
        static let LANDING_PAGE = "ViewController"
    }
    struct API {
        static let LOGIN_API = "login/login_ws.php/front"
        static let SEND_SMS = "sms/smsfintoo_ws.php/sendsms"
        static let CHECK_CREDENTIALS = "login/login_ws.php/checkcredentials"
        static let USER_EMAIL_MOBILE = "mintyapp/mintyapp_ws.php/useremailbymobile"
        //https://www.financialhospital.in/adminpanel/mintyapp/mintyapp_ws.php/useremailbymobile
        static let VALIDATE_PAN = "users/user_ws.php/validatepan"
        static let UPDATE_PAN = "users/user_ws.php/updatepan"
        static let SEND_SMS_OTP = "sms/smsfintoo_ws.php/sendsmsotp"
        static let SEND_MAIL = "email/email_ws.php/sendmail"
        static let UPDATE_MOBILE = "users/user_ws.php/UpdateMobile"
        static let REGISTER_USER = "users/user_ws.php/registerusermethod"
        static let MOBILE_UPDATE_MOBILE = "login/login_ws.php/checkupdmobile/"
        static let CHECK_PAN_DB = "users/user_ws.php/getuserdatabyid/"
        static let CHECK_USER_STAT = "users/user_ws.php/getuserprofilestat/"
        static let SEND_APP_EMAIL = "email/email_ws.php/mobileappmail"
        static let SEND_APP_EMAIL1 = "email/email_ws.php"
        static let RESET_PASSWORD = "login/login_ws.php/reset" // forgotpassword
        static let CHECK_FOR_OLD_PWD = "login/login_ws.php/checkpassword/"// CHECKING FOR OLD PASSWORD
        static let CHANGE_PASSWORD_UPDATE = "users/user_ws.php/updatepassword" // CHANGE PASSWORD
        static let PRODUCT_LIST = "schemedata/schemedata_ws.php/getSchemeList"//PRODUCT LIST
        static let GetAssetType = "schemedata/schemedata_ws.php/getAssetType"
        static let GetCategory = "schemedata/schemedata_ws.php/getCategory"
        static let GetFundOptions = "schemedata/schemedata_ws.php/getFundOptions"
        static let GetFundHouse = "schemedata/schemedata_ws.php/getFundHouse"
        static let GetRiskLevel = "schemedata/schemedata_ws.php/getRiskLevel"
        static let GetMinInvestment = "schemedata/schemedata_ws.php/getMinInvestment"
        static let Feedback = "users/user_ws.php/updatemobilefeedback"
        static let Cart_Count = "cart/cart_ws.php/getcartdetailsofuser/"
        static let Add_To_Cart = "cart/cart_ws.php/addtocart"
        static let Sip_start_days = "cart/cart_ws.php/getavlsipdays/"
        //static let send_email_addMember = "email/email_ws.php"
        static let Add_Member = "users/user_ws.php/updateuser/invshopaddmember"
        static let Member_List = "users/user_ws.php/getmembers/"
        static let getmemberswithparent = "users/user_ws.php/getmemberswithparent"
        static let GetUserData = "users/user_ws.php/getuserdatabyid/"
        static let GetCartData = "cart/cart_ws.php/getcartdetailsofuser/"
        static let UpdateCartData = "cart/cart_ws.php/updatecartuser"
        static let DeleteCart = "cart/cart_ws.php/deletecart"
        static let fetchPaymentTransactionData = "transaction/transaction_ws.php/fetchPaymentTransactionData"
        static let fetchTransactionIdData = "transaction/transaction_ws.php/fetchTransactionIdData"
        static let fetchTransactionIdUnitData = "transaction/transaction_ws.php/fetchTransactionIdUnitData"
        static let kycStatus = "kyc/kyc_ws.php/GetKycStatus/"
        static let userDoc = "kyc/kyc_ws.php/UserDocDetails/"
        static let addDoc = "kyc/kyc_ws.php/AddDocDetails"
        static let updatelatestbankmandate = "bank/bank_ws.php/updatelatestbankmandate"
        static let templates = "email/email_ws.php/sendmailfromapp"
        static let country = "fatca/fatca_ws.php/getCountries"
        static let state = "users/user_ws.php/showstates1/"
        static let city = "users/user_ws.php/showcity1/"
        static let getbankList = "bank/bank_ws.php/allbanks"
        static let bankType = "bank/bank_ws.php/allbanktypes"
        static let getMembers = "users/user_ws.php/getmembers"
        static let  addkyc = "kyc/kyc_ws.php/AddKycDetails"
        static let getKyc = "kyc/kyc_ws.php/UserKycDetails/"
        static let checkAadhar = "users/user_ws.php/checkadhar?exclude=1&id="
        static let deleteBank = "users/user_ws.php/deletebank"
        static let updateEmailCheck = "users/user_ws.php/verifyemailid"
        static let uploadDoc = "document/document_ws.php/uploaddocument"
        static let addBank = "bank/bank_ws.php/AddBankDetails"
        static let getBank = "bank/bank_ws.php/UserBankDetails/"
        static let getBankMandateDocs = "users/user_ws.php/getmandatestatbyuserbank/"
        //static let getBank = "users/user_ws.php/getmandatestatbyuserbank/"
        static let postUserData = "users/user_ws.php/updateuser/invshop"
        static let addFatca = "fatca/fatca_ws.php/AddFatcaDetails"
        static let addNRiDetails = "users/user_ws.php/SaveNRIDetails"
        static let  getOccupation = "fatca/fatca_ws.php/getOccupations"
        static let  getLocations = "fatca/fatca_ws.php/getLocations"
        static let  getTaxStatus = "fatca/fatca_ws.php/getTaxStatus"
        static let  getNriDetails = "users/user_ws.php/UserNRIDetails/"
        static let getFatcaDetails = "fatca/fatca_ws.php/UserFatcaDetails/"
        static let getIncomeSlabList = "fatca/fatca_ws.php/getIncomeSlabList"
        static let  updateimg = "users/user_ws.php/updateimg"
        static let checkparentpan = "users/user_ws.php/checkparentpan?exclude=1&id="
        static let addToCart = "cart/cart_ws.php/addtocart"
        static let fetchHolidayList = "cron/cron_ws.php/fetchholidaylist"
        static let getserverdatetime = "users/user_ws.php/getserverdatetime"
        static let addtostpswpcart = "cart/cart_ws.php/addtostpswpcart"
        static let calculatesipdate = "cart/cart_ws.php/calculatesipdate"
        static let add_pick_investment = "pickinvest/pickinvest_ws.php/add_pick_investment"
        static let get_pick_logic = "pickinvest/pickinvest_ws.php/get_pick_logic"
        static let getPickInvestList = "/schemedata/schemedata_ws.php/getPickInvestList"
        static let deleteNominee = "users/user_ws.php/deletenominee"
        static let AddNomineeDetails = "nominee/nominee_ws.php/AddNomineeDetails"
        static let nomineeAddmember = "users/user_ws.php/addmember"
        static let getNomineeDetails = "nominee/nominee_ws.php/UserNomineeDetails/"
        static let SetGetDefaultNominee = "nominee/nominee_ws.php/SetGetDefaultNominee/"
        static let getSelectAddressType = "document/document_ws.php/fetchdocumenttypelist/4"
        static let getTimeSlot = "document/document_ws.php/fetchtimeslots"
        static let getTransactionDetail = "wbr/wbr_ws.php/getWBRtransactions/"
        static let getRequestReport = "users/user_ws.php/reportreq"
        static let getReportPdf = "transaction/transaction_ws.php/generatePdfOfPortfolio"
        static let sendTxnReport = "transaction/transaction_ws.php/sendMailofTransactions"
        static let generatePDFofTxn = "transaction/transaction_ws.php/generatePdfOfPortfolio"
        static let getUsersPortfolio = "wbr/wbr_ws.php/getUsersPortfolio/"
        static let showscheme  = "schemedata/schemedata_ws.php/showscheme"
        static let showschemeAsset = "schemedata/schemedata_ws.php/schemeasset"
        static let feedFile = "feedfile/feedfile_ws.php/"
        static let updateGenerateFileStatus = "transaction/transaction_ws.php/UpdateTxnValueStatus"
        static let getMonth = "cart/cart_ws.php/getavlsipdays/"
        static let updateCart = "cart/cart_ws.php/updatecart"
        static let deleteCart = "cart/cart_ws.php/deletecart"
        static let getSOfundsofuser = "transaction/transaction_ws.php/getSOfundsofuser/"
        static let getrandomstring = "settings/cutoffservice_ws.php/getrandomstring"
        static let getSIfundsofuser = "transaction/transaction_ws.php/getSIfundsofuser/"
        static let generateAOF = "https://www.fintoo.in/generate_pdf/generate_aof_pdf.php?id="
        //static let generateAOF = "http://newinvest.erokda.in/generate_pdf/generate_aof_pdf.php?id="
        static let getUsedMandateAmount = "bank/bank_ws.php/getusedmandateamount"
        static let getUsedMandateForm = "https://www.fintoo.in/generate_pdf/generate_sip_pdf.php?id="
       // static let getUsedMandateForm = "http://newinvest.erokda.in/generate_pdf/generate_sip_pdf.php?id="
        static let getBankDoc = "https://www.fintoo.in/downloadglobalfile.php?filename="
       // static let getBankDoc = "http://newinvest.erokda.in/downloadglobalfile.php?filename="
        static let kycViewDoc = "https://www.fintoo.in/downloadglobalfile.php?filename="
        //static let kycViewDoc = "http://newinvest.erokda.in/downloadglobalfile.php?filename="
        static let getAssettype = "settings/cutoffservice_ws.php/getAssettype/"
        static let gettermvalue   = "users/user_ws.php/gettermvalue"
        static let addTransaction = "transaction/transaction_ws.php/addtransaction"
        static let getCurriorData = "transaction/transaction_ws.php/getconfirmdocdata"
        static let addmandateform = "bank/bank_ws.php/addmandateform"
        static let fetchAOFfileofUser = "document/document_ws.php/FetchAOFfileofUser"
        static let get_txns_nominee = "transaction/transaction_ws.php/get_txns_nominee"
        static let addtransnominee = "transaction/transaction_ws.php/addtransnominee"
        static let updatetransaction = "transaction/transaction_ws.php/updatetransaction"
        static let gettransactiondetails = "transaction/transaction_ws.php/gettransactiondetails"
        static let  canceltxn = "transaction/transaction_ws.php/canceltxn"
        static let getFoliandAMCbyPAN = "wbr/wbr_ws.php/getFoliandAMCbyPAN"
        static let updateTransactionandCartFolio = "transaction/transaction_ws.php/updateTransactionandCartFolio"
        static let SingleBankDetail = "bank/bank_ws.php/SingleBankDetail"
        static let addtxnlogin  = "transaction/transaction_ws.php/addtxnlogin"
        static let downloadKyc = "https://www.fintoo.in/generate_pdf/generate_pdf.php?id="
        //static let downloadKyc = "http://newinvest.erokda.in/generate_pdf/generate_pdf.php?id="
        static let showschemes = "settings/cutoffservice_ws.php/showschemes/"
        static let SIP_addtocart  = "cart/cart_ws.php/SIP_addtocart"
        static let productlist = "https://www.fintoo.in/productlist.php"
        static let pg_dump_php = "https://www.fintoo.in/mobileapp/pg_dump.php"
        //static let  pg_dump_php = "http://www.erokda.in/mobileapp/pg_dump.php"
        static let get_pick_invest_plans = "pickinvest/pickinvest_ws.php/get_pick_invest_plans/"
        //static let addmandateform = "bank/bank_ws.php/addmandateform"

        //bse api
        static let scanmandateimageupload = "bse/bse_ws.php/ScanMandateImageUpload/"
        static let  isBSERegistered = "bse/bse_ws.php/isBSERegistered/"
        static let  AOFImageUpload = "bse/bse_ws.php/AOFImageUpload/"
        static let  MandateRegister = "bse/bse_ws.php/MandateRegister/"
        static let  clientregistration = "bse/bse_ws.php/clientregistration/"
        static let  FATCAUpload = "bse/bse_ws.php/FATCAUpload/"
        static let  gettxnstatusbyuser = "transaction/transaction_ws.php/gettxnstatusbyuser/"
        static let  NormalOrderEntry = "bse/bse_ws.php/NormalOrderEntry/"
        static let  SwitchOrderEntry = "bse/bse_ws.php/SwitchOrderEntry/"
        static let  SWPRegistration  = "bse/bse_ws.php/SWPRegistration/"
        static let  STPRegistration = "bse/bse_ws.php/STPRegistration/"
        static let XSIPOrderEntry = "bse/bse_ws.php/XSIPOrderEntry/"
        static let ISIPOrderEntry = "bse/bse_ws.php/ISIPOrderEntry/"
        static let STPCancellation = "bse/bse_ws.php/STPCancellation"
        static let SWPCancellation = "bse/bse_ws.php/SWPCancellation"
        static let updatemandatetype = "bank/bank_ws.php/updatemandatetype"
        static let ScanMandateImageUpload = "bse/bse_ws.php/ScanMandateImageUpload/"
        static let addpaymentmode = "transaction/transaction_ws.php/addpaymentmode"
        static let paymentGateway = "bse/bse_ws.php/paymentGateway"
        static let paymentGatewayResponse = "bse/bse_ws.php/paymentGatewayResponse/"
        static let postofficeapi = "/users/user_ws.php/postofficeapi/"
        static let getriskprofile = "fhc/fhc_ws.php/getriskprofile/"
        static let getriskassessmentset = "fhc/fhc_ws.php/getriskassessmentset/1"
        static let adduserriskassessment = "fhc/fhc_ws.php/adduserriskassessment"
        static let getSchemeListCount = "schemedata/schemedata_ws.php/getSchemeListCount"
        static let mobile_payment_logout = "https://www.fintoo.in/mobile_payment_logout.php"
    }

    struct User_Defaults {
        static let MOBILE_NUMBER = "Mobile"
        static let PROFILE_IMG = "profile_img"
        static let USER_ID = "userid"
        static let parent_user_id = "parent_user_id"
        static let EMAIL = "Email"
        static let USER_LOGIN = "userLogIn"


    }
}
